services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /frontend/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

